### ISSUE TITLE
accept a suggestion?

### ISSUE THREAD

**Issue by reagle** [priner/micro-aspell-plugin#1]
This is fantastic, thank you!

Will it be possible to support replacing a mispelled word with a suggested one?

**Comment by priner** [comment]
Thank you for the kind words!

This is something I thought about but I'm not sure what would be the right approach. I could add it as a command, like `accept n` to accept the n-th suggestion. One small downside is that you wouldn't be able to see the suggestions while typing that command as they are displayed in the same line as commands. This one would be pretty straightforward to implement.

I was also thinking about doing something more fancy that would cycle through the suggestions like autocomplete does. I'm not quite sure this is possible but i will definitely look into this.
