### ISSUE TITLE
Ability to disable/enable spellchek with a command

### ISSUE THREAD

**Issue by hroncok** [priner/micro-aspell-plugin#15]
Is there a way I can disable/enable spellcheck of an already opened file?

I can run `setlocal aspell.check on`/`off` but that seems to behave rather odd - it only starts happening when I change the buffer.

I guess adding a custom command that does the above + calls `spellcheck(bp.Buf)` might work. I can try submitting a PR if this would be acceptable.

**Comment by priner** [comment]
yeah, I would merge that. This has come up before https://github.com/priner/micro-aspell-plugin/issues/11#issue-925647899 but that one doesn't work correctly with `aspell.check = auto`.

**Comment by hroncok** [comment]
Well, my idea was not a toggle command, but a disable/enable commands. So it would override auto I guess. A toggle might be nice, but harder.

**Comment by hroncok** [comment]
Oh, I see b9e43770bc9a4b86cc092b4546c87c5c441b9cb0 -- thanks!
