### ISSUE TITLE
How do I change the dictionary/language without editing the settings file each time?

### ISSUE THREAD

**Issue by iio7** [priner/micro-aspell-plugin#9]
As the title says, is it not possible to change language while editing, or at least during load WITHOUT changing the settings file each time?

**Comment by priner** [comment]
You can change any setting from within micro with `set` or `setlocal` commands. See `help commands`.

Use `setlocal` command to change `aspell.lang` or really any other setting just for the current buffer (won't be saved to the setting file).

**Comment by iio7** [comment]
Thank you very much.
